version: '2.1'
orbs:
  docker: circleci/docker@2.4.0
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: favish/cloud-command-drupal
          update-description: true
          tag: $CIRCLE_TAG
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context:
            - dockerhub